using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Users.Domain.Aggregates;
using Users.Domain.Rules;

namespace Users.Infrastructure.Persistence.Configuration;

public class UserConfig : IEntityTypeConfiguration<User>
{
    private readonly IUserDomainRulesConfigProvider userDomainRulesConfigProvider;
    public UserConfig(IUserDomainRulesConfigProvider userDomainRulesConfigProvider)
    {
        this.userDomainRulesConfigProvider = userDomainRulesConfigProvider;
    }
    public void Configure(EntityTypeBuilder<User> builder)
    {
        // maps entity to a table
        builder.ToTable("Users");
        // set primary key
        builder.HasKey(user => user.Id);
        // disable autogenerated value
        builder.Property(user => user.Id).ValueGeneratedNever();

        // makes field required
        builder.Property(user => user.Role).IsRequired();
        
        // build field from value object
        builder.OwnsOne(user => user.UserName,username =>
        {
            username.Property(un => un.Value)
                .HasColumnName("UserName")
                .IsRequired()
                .HasMaxLength(userDomainRulesConfigProvider.UserNameDomainRules.MaxLength);
            
            username.HasIndex(un => un.Value).IsUnique().HasDatabaseName("IX_Users_UserName");
        });

        builder.OwnsOne(user => user.Email,email =>
        {
            email.Property(e => e.Value)
                .HasColumnName("Email")
                .IsRequired();
        
            email.HasIndex(e => e.Value).IsUnique().HasDatabaseName("IX_Users_Email");
        });

        builder.OwnsOne(user => user.HashedPassword,hashedPassword =>
        {
            hashedPassword.Property(hash => hash.Value)
                .HasColumnName("HashedPassword")
                .IsRequired();
        });


        builder.Ignore(user => user.Events);
    }
}